### ISSUE TITLE
Cleanup duplicate scripts

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon-scripts#30]
Remove any old test or otherwise depreciated versions of covid_19/robbie and patient_assistant/pat scripts

**Comment by NeonDaniel** [comment]
https://github.com/NeonGeckoCom/neon-scripts/pull/32/files

@NeonAndrii, it looks like the pat script here isn't working as expected; I just get the time back after giving my name. Please look into this when you get a chance.

**Comment by NeonAndrii** [comment]
@NeonDaniel I've tested the script again and it works as intended. Could you provide the logs?

**Comment by NeonDaniel** [comment]
Sorry for the false alarm; it looks like there was an issue with updates on the server...
